### YamlMime:Landing
title: Dokumentation zu Docker in Azure
summary: 'Docker ist eine beliebte Plattform für die Containerverwaltung und Imageerstellung, die es Ihnen ermöglicht, schnell mit Containern unter Linux und Windows zu arbeiten. Erfahren Sie, wie Sie Docker in Azure nutzen:'
metadata:
  title: Dokumentation zu Docker in Azure
  description: 'Docker ist eine beliebte Plattform für die Containerverwaltung und Imageerstellung, die es Ihnen ermöglicht, schnell mit Containern unter Linux und Windows zu arbeiten. Erfahren Sie, wie Sie Docker in Azure nutzen:'
  services: multiple
  ms.service: multiple
  ms.topic: landing-page
  author: georgewallace
  ms.author: gwallace
  ms.date: 03/08/2020
  ms.openlocfilehash: daff334cbbe118d6fdbc42a5497313f9671fd7f1
  ms.sourcegitcommit: 8f4d54218f9b3dccc2a701ffcacf608bbcd393a6
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 03/09/2020
  ms.locfileid: "78944024"
landingContent:
- title: Bereitstellen von Docker in Azure
  linkLists:
  - linkListType: overview
    links:
    - text: Bereitstellen der Schnellstartvorlage „Docker on Ubuntu Server“
      url: https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/
- title: Erste Schritte
  linkLists:
  - linkListType: tutorial
    links:
    - text: Ausführen einer Python-Web-App (Django) mit PostgreSQL in Azure App Service
      url: ../app-service/containers/tutorial-python-postgresql-app.md
    - text: Erstellen einer Entwicklungsinfrastruktur auf einem virtuellen Linux-Computer in Azure mit Jenkins, GitHub und Docker
      url: ../jenkins/tutorial-jenkins-github-docker-cicd.md
- title: Ressourcen
  linkLists:
  - linkListType: reference
    links:
    - text: Docker-Azure-Website
      url: https://docs.docker.com/docker-for-azure/why/
    - text: Docker-Azure-Treiber
      url: https://docs.docker.com/machine/drivers/azure/
    - text: Informationen zu Docker
      url: https://docker.com
