- name: Docker-Dokumentation
  href: index.md
- name: Schnellstart
  expanded: true
  items:
    - name: Docker-Marketplace-Vorlage
      href: 'https://azuremarketplace.microsoft.com/en-us/marketplace/apps/CanonicalandMSOpenTech.DockerOnUbuntuServer1404LTS'
- name: Tutorials
  items:
    - name: Python-Web-App mit Docker und PostgreSQL
      href: /azure/app-service-web/app-service-web-tutorial-docker-python-postgresql-app
    - name: CD/CI mit Docker Swarm und VSTS
      href: /azure/container-service/container-service-docker-swarm-mode-setup-ci-cd-acs-engine
    - name: 'CI/CD mit Docker, Jenkins und Linux'
      href: /azure/virtual-machines/linux/tutorial-jenkins-github-docker-cicd
- name: Anleitungen
  items:
    - name: Docker-VM-Erweiterung
      href: /azure/virtual-machines/linux/dockerextension
    - name: Docker-Computer
      href: /azure/virtual-machines/linux/docker-machine
    - name: Docker-Containerregistrierung
      href: /azure/container-registry/container-registry-get-started-portal
- name: angeben
  items:
    - name: Azure-Roadmap
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Docker-Azure-Treiber
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Docker-Azure-Website
      href: 'https://www.docker.com/docker-azure'
    - name: Docker-Website
      href: 'https://docker.com'