### YamlMime:YamlDocument
documentType: LandingData
title: Ansible in der Azure-Dokumentation
metadata:
  title: Ansible in der Azure-Dokumentation – Tutorials, Beispiele, Referenz und Ressourcen
  meta.description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 07/05/2018
  ms.author: tarcher
  ms.openlocfilehash: 3d885c6374530884e761ecbee837d6406dd3e894
  ms.sourcegitcommit: ab3b2482704758ed13cccafcf24345e833ceaff3
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 07/06/2018
  ms.locfileid: "37868604"
abstract:
  description: Verwenden Sie <a href="http://www.ansible.com">Ansible</a> zum Automatisieren von Cloudbereitstellung, Konfigurationsverwaltung und Anwendungsbereitstellungen.
sections:
- title: Fünfminütige Schnellstarts
  items:
  - type: paragraph
    text: Konfigurieren Sie Ansible, und verwenden Sie das Tool zum Erstellen eines virtuellen Linux-Computers in Azure.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Konfigurieren von Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Erstellen eines virtuellen Linux-Computers
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Schritt-für-Schritt-Tutorials
  items:
  - type: paragraph
    text: Hier erfahren Sie, wie Sie mit Ansible eine Compute- und Netzwerkinfrastruktur in Azure erstellen und verwalten.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Erstellen eines virtuellen Linux-Computers, einschließlich virtuellem Netzwerk, öffentlicher IP-Adresse und virtueller Netzwerkkarte</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Herstellen einer Verbindung mit einem virtuellen Azure-Computer und Ausführen eines Ansible Playbooks in Cloud Shell</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Erstellen und Verwalten eines dynamischen Bestands Ihrer Azure-Ressourcen</a>
- title: Verweis
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Playbook-Rollen
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Releases und Features
      html: <p><a href="./ansible-matrix.md">Featurematrix für Module und Rollen</a></p>
    - title: Tools
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Visual Studio Code-Erweiterung für Ansible</a></p>
