### YamlMime:YamlDocument
ms.openlocfilehash: 9f537ee8fe646a024fb191901b3669b4b5d60d6b
ms.sourcegitcommit: f6e2a03076679d53b550a24828141c4fb978dcf9
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 08/27/2018
ms.locfileid: "43086668"
documentType: LandingData
title: Ansible in der Azure-Dokumentation
metadata:
  title: Ansible in der Azure-Dokumentation – Tutorials, Beispiele, Referenz und Ressourcen
  description: Hier erfahren Sie, wie Sie Ansible zum Automatisieren von Cloudbereitstellung, Konfigurationsverwaltung und Anwendungsbereitstellungen verwenden.
  ms.service: ansible
  keywords: Ansible, Azure, DevOps, Tutorials, Beispiele, Referenz
  author: tomarcher
  manager: jeconnoc
  ms.author: tarcher
  ms.topic: landing-page
  ms.date: 08/27/2018
abstract:
  description: Verwenden Sie <a href="http://www.ansible.com">Ansible</a> zum Automatisieren von Cloudbereitstellung, Konfigurationsverwaltung und Anwendungsbereitstellungen.
sections:
- title: Fünfminütige Schnellstarts
  items:
  - type: paragraph
    text: Installieren Sie Ansible, und verwenden Sie es zum Erstellen und Verwalten von virtuellen Linux-Computern in Azure.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Installieren von Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Erstellen eines virtuellen Linux-Computers
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Verwalten eines virtuellen Linux-Computers
      href: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Schritt-für-Schritt-Tutorials
  items:
  - type: paragraph
    text: Hier erfahren Sie, wie Sie mit Ansible eine Compute-, Netzwerk- und Speicherinfrastruktur in Azure erstellen und verwalten.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Erstellen eines virtuellen Linux-Computers, einschließlich virtuellem Netzwerk, öffentlicher IP-Adresse und virtueller Netzwerkkarte</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Ausführen von Ansible mit Bash in Azure Cloud Shell</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Erstellen und Verwalten eines dynamischen Bestands Ihrer Azure-Ressourcen</a>
    - html: <a href="./ansible-create-configure-vmss">Erstellen und Verwalten von Skalierungsgruppen für virtuelle Computer in Azure</a>
    - html: <a href="./ansible-deploy-app-vmss">Bereitstellen von Anwendungen für VM-Skalierungsgruppen in Azure</a>
    - html: <a href="./ansible-create-configure-aks">Erstellen und Verwalten von Azure Kubernetes Service-Clustern</a>
- title: Verweis
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Playbook-Rollen
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Releases und Features
      html: <p><a href="./ansible-matrix.md">Featurematrix für Module und Rollen</a></p>
    - title: Tools
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Visual Studio Code-Erweiterung für Ansible</a></p>
