items:
- name: Dokumentation zu Ansible in Azure
  href: ./index.yml
- name: Übersicht
  items:
  - name: Informationen zu Ansible in Azure
    href: ./ansible-overview.md
- name: Schnellstarts
  items:
  - name: Installieren von Ansible auf einem virtuellen Linux-Computer
    href: /azure/virtual-machines/linux/ansible-install-configure
    maintainContext: true
  - name: Erstellen eines virtuellen Linux-Computers
    href: /azure/virtual-machines/linux/ansible-create-vm
    maintainContext: true
  - name: Verwalten eines virtuellen Linux-Computers
    href: /azure/virtual-machines/linux/ansible-manage-linux-vm
    maintainContext: true
  expanded: true
- name: Lernprogramme
  items:
  - name: Ausführen eines Playbooks in Cloud Shell
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: Verwalten von dynamischen Beständen
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
  - name: Erstellen und Konfigurieren von VMSS
    href: ./ansible-create-configure-vmss.md
  - name: Bereitstellen von Apps in VMSS
    href: ./ansible-deploy-app-vmss.md
  - name: Autoskalierung von VMSS
    href: ./ansible-auto-scale-vmss.md
  - name: Erstellen und Konfigurieren von AKS-Clustern
    href: ./ansible-create-configure-aks.md
  - name: Erstellen und Konfigurieren einer Azure Application Gateway-Instanz
    href: ./ansible-create-configure-application-gateway.md
  - name: Erstellen und Konfigurieren einer Azure DB for MySQL-Instanz
    href: ./ansible-create-configure-mysql.md
  - name: Erstellen und Konfigurieren von Azure-Web-Apps
    href: ./ansible-create-configure-azure-web-apps.md
  - name: Skalieren von Azure-Web-Apps
    href: ./ansible-scale-azure-web-apps.md
- name: Verweis
  items:
  - name: Playbook-Rollen
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Releases und Features
    href: ./ansible-matrix.md
  - name: Azure Container Instances
    href: https://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure-Funktionen
    href: https://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Load Balancer
    href: https://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Virtuelle Computer
    href: https://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: Alle Module für Azure
    href: https://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: Tools
  items:
  - name: Visual Studio Code-Erweiterung für Ansible
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
ms.openlocfilehash: f426841f2a02b085e34e9e2a768c43a052bf62f7
ms.sourcegitcommit: c37122644eab1cc739d735077cf971edb6d428fe
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 12/14/2018
ms.locfileid: "53409135"
